<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);PublicWeb.Tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Seo\Fonts\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Seo\Assets\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
