name: Deploy Public Web

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: ./public-web
      run: dotnet restore

    - name: Build
      working-directory: ./public-web
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      working-directory: ./public-web
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "public-web/publish/*"
        target: "/home/lucas/apps/futbolnet/web"
        strip_components: 2

    - name: Restart Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl restart futbolnet-web
